# Generated by Django 4.0.2 on 2022-03-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(max_length=200),
        ),
    ]
